### ISSUE TITLE
D10 and D100 both recognized as D10

### ISSUE THREAD

**Issue by Gyrior** [foundryvtt/pixels#10]
I have four 10 sided dice, for making two D100. But the integration recognices all four as D10 with numbers from 1 to 10. I don't have options to change this. Is there a way to configure these correctly?
Foundry 

![Physical Dice](https://github.com/user-attachments/assets/cb813449-6e50-4552-a978-1a9bf2168ff9)
![image](https://github.com/user-attachments/assets/00f851f5-cb1b-46ea-8e2f-db330dc4f56e)
![image](https://github.com/user-attachments/assets/a1a52584-7299-4d0a-a8c6-9fda6cab7c7f)

**Comment by pavalanche** [comment]
Exactly same problem here.

**Comment by FredisMyEvilTwin** [comment]
My D4 are also reporting in foundry as D6s (I currently have 2, both reporting incorrectly). My module is at 0.2.0, and all dice have been updated on the firmware side. This seems like it could be the same issue, which is why I just added my comment here instead of creating a new one. If I should have gone that route, just let me know.

**Comment by blalasaadri** [comment]
It seems that the integration is using the [`dieFaceCount`](https://github.com/GameWithPixels/pixels-js/blob/main/packages/pixels-core-connect/src/Pixel.ts#L335) rather than the [`dieType`](https://github.com/GameWithPixels/pixels-js/blob/main/packages/pixels-core-connect/src/Pixel.ts#L330). And since both D10s and D%s have 10 sides, the integration cannot tell them apart.

I assume that [this line](https://github.com/foundryvtt/pixels/blob/main/scripts/manager.mjs#L104) is the culprit.

**Comment by Fyorl** [comment]
I've added some experimental handling for percentile die rolls, but as I do not own a set myself, it's difficult to test. Please try with the 1.0 version of the module and report back.

**Comment by Gyrior** [comment]
For me it is working now.
