### ISSUE TITLE
Incorrect/Unintended Rolls

### ISSUE THREAD

**Issue by umop3plsdn3dlus** [foundryvtt/pixels#8]
Issue - After making an intended roll using the prompts, foundry will auto populate another roll even though dice was not rolled and is at rest. 

When this issue happens, sometimes the false rolled result will auto populate into the *next* intended roll, regardless of the physical result of pixels. then it will populate the correct roll as an unintended roll, and the pattern continues until I reload.

![IMG20240930224557](https://github.com/user-attachments/assets/092b0acf-ffd8-49ad-88e7-bc1b75c97321)
You can see in this pic the physical die is on a 12, but the intended roll was registered as an 11, and then the duplicate unintended roll registers as a 12

This is from the console at the time of rolling https://pastebin.com/EcEQEnF1

May register the instant I pick up the dice as a roll? even though I try to move fast to keep it from false rolling. Would adding a delay help? Thanks for your help. Feel free to ping me here or in the Pixels discord for more information if needed - umop3plsdn3dlus

**Comment by blalasaadri** [comment]
I'm pretty sure that the assumption
> May register the instant I pick up the dice as a roll?

is correct. When I use my Pixel with Foundry, I make sure to keep it moving all the time until it lands on whatever number it's going to land on because of this - in that case it just records the one roll. So this is likely a case of sensitivity and false rolls.

If so, it will be at least partially fixed with the sensitivity firmware update for the Pixels, which will hopefully happen soon. So that's good.

But: the Foundry integration could also do some things here.
Firstly, someone could add a debounce similar to what the Pixels dndbeyond integration has (check [here](https://github.com/carrierfry/pixels-dndbeyond-userscript/blob/38d4755199576cd5129d7916cbcc9d3ccf654049/pixels-dndbeyond.user.js#L1798) for that logic) so it ignores that first fake roll.

Secondly, logic could be added so that the player has to actually request a roll in order for it to be registered by this integration. That may add a few additional clicks, but it reduces the number of false rolls considerably.

**Comment by Fyorl** [comment]
We've added a debounce which should improve the situation here, combined with the new firmware.
